# this workflow is used to executed Synapse activity if new pubs are 
# identified or if updates are needed

name: synapse_updates_cicd

on:
  push:
    branches: [main]
    paths: 
      - 'publication_updates.csv'
      - 'new_publications.csv'
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'The commit message to use'
        required: true
        default: 'Manual execution via workflow_dispatch'

jobs:
  update-synapse:
    name: Synapse Updates CI/CD
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ARK_CICD_SERVICE_ACCOUNT }}
      SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
    
    steps:
      - name: Checkout Repositoy
        uses: actions/checkout@v6
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: main
          token: ${{ secrets.ARK_CICD_SERVICE_ACCOUNT }}

      # Set up supported python.
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10.19'

      - name: Install Python Packages
        run: |
          pip install "synapseclient[pandas]"

      - name: logical tests for which files have changed
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            new:
              - 'new_publications.csv'
            updates:
              - 'publication_updates.csv'

      # run only if 'new' files were changed
      - name: Create new publication link entities
        if: steps.filter.outputs.new == 'true'
        run: |
          python utils/create_new_pub_entities.py && echo 'New publications created!'

      # run only if 'updates' files were changed
      - name: Create new publication link entities
        if: steps.filter.outputs.updates == 'true'
        run: |
          python utils/update_pub_entities.py && echo 'Publications updated!'

      # update backend Table to surface changes on Portal
      - name: Update Portal - Publications Table
        run: |
          python portal_publications_update.py && echo 'Portal publications updated!'

# END